IceCreamStore/urls.py
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    url(r'^admin/', admin.site.urls),
    url(r'^store/', include("store.urls")),
    url(r'^.*$', RedirectView.as_view(url='/store/', permanent=False))
]  

store/urls.py
from django.conf.urls import url
#from django.contrib import admin
from . import views

urlpatterns = [
        url(r'^$', views.index.as_view(), name='index'),
        url(r'^register/?$', views.register.as_view(), name='register'),
        url(r'^product/?$', views.all_product.as_view(), name='all_product'),
        url(r'^popular_product/?$', views.popular_product.as_view(), name='popular_product'),
        url(r'^product/(?P<product_id>[0-9]+)/?$', views.product.as_view(), name='product'),
        url(r'^product/vote/(?P<product_id>[0-9]+)/?$', views.user_vote.as_view(), name='user_vote'),
        url(r'^history/?$', views.history.as_view(), name='history'),
        url(r'^track/?$', views.all_track.as_view(), name='all_track'),
        url(r'^track/(?P<track_id>[0-9]+)/?$', views.track.as_view(), name='track'),
        url(r'^profile/?$', views.profile.as_view(), name='profile'),
        url(r'^contact_us/?$', views.contact_us.as_view(), name='contact_us'),
        # TODO: fix url redirection
        url(r'^login/?$', views.login_view.as_view(), name='login_view'),
        url(r'^logout/?$', views.logout_view.as_view(), name='logout_view'),
        url(r'^cart/?$', views.cart.as_view(), name='cart'),
        url(r'^cart/delete/(?P<cart_id>[0-9]+)/?$', views.delete_cart.as_view(), name='delete_cart'),
        url(r'^purchase/?$', views.purchase.as_view(), name='purchase'),
        url(r'^clearcart/?$', views.clear_cart.as_view(), name='clear_cart'),
        url(r'^.*$', views.index.as_view(), name='somethingelse'),
]

store/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User, AbstractUser
from datetime import datetime
from django.db.models.query import EmptyQuerySet

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=400)
    image = models.ImageField(upload_to='media/media/product_image/', default='media/media/product_image/None/no-img.jpg')
    amount = models.IntegerField()
    price = models.FloatField()
    score = models.FloatField(default=0)
    voter = models.IntegerField(default=0)
    
    def add_or_update(self):
        defaults = {
            'name':self.name,
            'description':self.description,
            'image':self.image,
            'amount':self.amount,
            'price':self.price,
            'score':self.score    
        }
        obj, created = Product.objects.update_or_create(id=self.id,defaults=defaults)
        return created

    def __unicode__(self):
        return self.name

class CustomUser(AbstractUser):
    address = models.CharField(max_length=300)
    tel = models.CharField(max_length=20)
    company = models.CharField(max_length=50)
    user_cart = models.ManyToManyField(Product, through='Cart')

    def purchase(self):
        if self.user_cart.all().count() == 0:
            return False
        order = Order(user=self,sum_price=0)
        order.save()
        for product in self.user_cart.all():
            item = Cart.objects.get(user=self, product=product)
            order.sum_price += item.qty * product.price
            product.amount -= item.qty
            product.add_or_update()
            OrderList(order=order, product=product, qty=item.qty).save()
        self.user_cart.clear()
        order.save()
        Tracking(order=order, user=self).add_or_update()
        return True

class VoteProduct(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    score = models.FloatField(default=0)

    def user_vote_or_update_score(self):
        '''
            This method basically change user score if exists else create new voteproduct object which mean one user can only vote one time for each product.
        but user can change their vote score instead of create new one
        '''
        try:
            obj = VoteProduct.objects.get(user=self.user, product=self.product)
            self.product.score = ((self.product.score*self.product.voter) - obj.score + self.score)/self.product.voter
            obj.score = self.score
            obj.save()
        except VoteProduct.DoesNotExist:
            temp_score = self.product.score*self.product.voter
            self.product.voter += 1
            self.product.score = (temp_score + self.score)/self.product.voter
            self.save()
        self.product.save()
        #obj, created = VoteProduct.objects.get_or_create(user=self.user, product=self.product, defaults={'score':0})

class Order(models.Model):
    date = models.DateField(auto_now_add=True)
    sum_price = models.FloatField()
    list_product = models.ManyToManyField(Product, through='OrderList')
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)


class OrderList(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    qty = models.IntegerField()
    date = models.DateTimeField(auto_now=True)

class Tracking(models.Model):
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    STATE_CHOICE = (
        (1 , 'Processing'),
        (2 , 'Preparing'),
        (3 , 'Delivering'),
        (4 , 'Success'),
    )
    current_state = models.IntegerField(choices=STATE_CHOICE, default=1)
    date = models.DateTimeField(auto_now=True)

    def add_or_update(self):
        obj, created = Tracking.objects.update_or_create(order=self.order, user=self.user, current_state=self.current_state)
        return created

class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField()

    def add_or_update(self):
        obj, created = Cart.objects.update_or_create(user=self.user, product=self.product, defaults={'qty':self.qty})
        return created

store/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
        file = forms.FileField()

store/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response, redirect, get_object_or_404, HttpResponseRedirect
from django.views import View
from django.views.decorators.csrf import ensure_csrf_cookie
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.db import connection, IntegrityError
from django.contrib import messages
from .models import *
from django.http import Http404
from django.utils.datastructures import MultiValueDictKeyError
from django.core import serializers
from django.http import JsonResponse, HttpResponse
import json
import sys

# Create your views here.
class index(View):
    template_name = "store/index.html"
    def get(self, request):
        #obj, created = User.objects.get_or_create(username="admin", password="1234", isAdmin=True)
        #print created
        if not request.user.is_authenticated():
            return HttpResponseRedirect("/store/product")  

        history = Tracking.objects.filter(user=request.user, current_state=4).count()
        track = Tracking.objects.filter(user=request.user).exclude(current_state=4).count()
        product = Product.objects.all().count()
        cart = Cart.objects.filter(user=request.user).count()

        return render(request, self.template_name, {'history': history, 'track': track, 'cart': cart, 'product': product})


class login_view(View):
    template_name = "store/login.html"
    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        user = authenticate(username=username, password=password)
        next_page = ""
        if user is not None:
            login(request, user)
            if "next" not in request.GET:
                next_page = "/store/"
            else:
                next_page = request.GET['next']
            return HttpResponseRedirect(next_page)
        return render(request, self.template_name, {'err_message': 'Invalid username/password'})

class register(View):
    template_name = "store/register.html"

    # @method_decorator(login_required)
    def get(self, request):
        #if not 'is_logged_in' in request.session or not request.session['is_logged_in']:
        #    return redirect("/store/login")
        return render(request, self.template_name, {})
      
    def post(self, request):
        response = {}
        for key in request.POST.keys():
            response[key] = request.POST.get(key, '')
        if CustomUser.objects.filter(username=response['username']).exists():
            messages.error(request, 'Username already exists', extra_tags='alert-danger')
        if response['username'] == "":
            messages.error(request, 'Username required', extra_tags='alert-danger')
        if response['password'] != response['repassword']:
            messages.error(request, 'Password not matched', extra_tags='alert-danger')
        if response['password'] == "":
            messages.error(request, 'Password required', extra_tags='alert-danger')
        if response['first_name'] == "":
            messages.error(request, 'Firstname can\'t be empty', extra_tags='alert-danger')
            response['err_message'] = "Null value at First Name"
        if response['last_name'] == "":
            messages.error(request, 'Lastname can\'t be empty', extra_tags='alert-danger')
        if response['email'] == "":
            messages.error(request, 'E-mail can\'t be empty', extra_tags='alert-danger')
        if response['address'] == "":
            messages.error(request, 'Address can\'t be empty', extra_tags='alert-danger')
        if response['tel'] == "":
            messages.error(request, 'Telephone can\'t be empty', extra_tags='alert-danger')
        if not list(messages.get_messages(request)):
            try:
                newUser = CustomUser(username=response['username'],
                               is_superuser=0,
                               first_name=response['first_name'],
                               last_name=response['last_name'],
                               email=response['email'],
                               address=response['address'],
                               tel=response['tel'],
                               company=response['company'])
                newUser.set_password(response['password'])
                newUser.save()
                messages.success(request, 'Register Complete', extra_tags='alert-success')
                return redirect('/store/login')
            except IntegrityError as e:
                response['err_message'] = "Username already exists(2)"
                response["password"] = ""
                response["repassword"] = ""
                return render(request, self.template_name, response)
        else:
            response["password"] = ""
            response["repassword"] = ""
            return render(request, self.template_name, response)

class all_product(View):
    template_name = "store/all_product.html"
    def get(self, request):
        response = {}
        products = Product.objects.all()
        response['products'] = products
        return render(request, self.template_name, response)

    @method_decorator(login_required)
    def post(self, request):
    	try:
            product_id = int(request.POST['product_id'])
            amount = int(request.POST['amount'])
            product = Product.objects.get(id=product_id)
            current_amount = product.amount
            if amount < 0 or amount > current_amount:
                return JsonResponse({"status": "invalid amount"})
            Cart(user=CustomUser.objects.get(id=request.user.id), product=product, qty=amount).add_or_update()
        except ValueError, MultiValueDictKeyError:
            raise Http404("product doesn't exists")
        return JsonResponse({"status": "success"})

class popular_product(View):
    template_name = "store/popular_product.html"
    def get(self, request):
        response = {}
        products = Product.objects.all().order_by('-score')
        response['products'] = products
        return render(request, self.template_name, response)

    @method_decorator(login_required)
    def post(self, request):
    	try:
            product_id = int(request.POST['product_id'])
            amount = int(request.POST['amount'])
            product = Product.objects.get(id=product_id)
            current_amount = product.amount
            if amount < 0 or amount > current_amount:
                return JsonResponse({"status": "invalid amount"})
            Cart(user=CustomUser.objects.get(id=request.user.id), product=product, qty=amount).add_or_update()
        except ValueError, MultiValueDictKeyError:
            raise Http404("product doesn't exists")
        return JsonResponse({"status": "success"})

class product(View):
    template_name = "store/product.html"

    def get(self, request, product_id):
        product = get_object_or_404(Product,pk=product_id)
        product = json.loads(serializers.serialize('json', [product])[1:-1])
        return JsonResponse(product)

    def post(self, request, product_id):
        pass

class history(View):
    template_name = "store/history.html"
    @method_decorator(login_required)
    def get(self, request):
        history = Tracking.objects.filter(user=request.user, current_state=4)
        return render(request, self.template_name, {"history":history})

class all_track(View):
    template_name = "store/all_track.html"
    @method_decorator(login_required)
    def get(self, request):
        tracks = Tracking.objects.exclude(current_state=4).filter(user=request.user)
        return render(request, self.template_name, {"tracks": tracks})

class track(View):
    template_name = "store/track.html"

    def get(self, request, track_id):
        pass

class profile(View):
    template_name = "store/profile.html"
     
    @method_decorator(login_required)
    def get(self, request):
        user = CustomUser.objects.get(id=request.user.id)
        return render(request, self.template_name, {'user': user})

    @method_decorator(login_required)
    def post(self, request):
        user = CustomUser.objects.get(id=request.user.id)
        user.first_name = request.POST.get('first_name', '')
        user.last_name = request.POST.get('last_name', '')
        user.address = request.POST.get('address', '')
        user.tel = request.POST.get('tel', '')
        authen = authenticate(username=user.username, password=request.POST.get('password', ''))
        if authen is not None:
            user.save()
            messages.success(request, "Successfully edited profile.", extra_tags="alert-info")
            return render(request, self.template_name)
        messages.error(request, "Invalid password", extra_tags="alert-danger")
        return render(request, self.template_name, {'user': user})


class contact_us(View):
    template_name = "store/contact_us.html"

    def get(self, request):
        return render(request, self.template_name, {
            'email':'kitchaphan.s@ku.th',
            'tel':'081-4623115',
            'address':'chapterone@kaset',
        })


class cart(View):
    template_name = "store/cart.html"

    @method_decorator(login_required)
    def get(self, request):
        user_cart = Cart.objects.filter(user=request.user)
        return render(request, self.template_name, {'user_cart': user_cart})

class delete_cart(View):
    def get(self, request, cart_id):
        try:
            x = Cart.objects.get(id=cart_id)
            x.delete()
        except Cart.DoesNotExist:
            messages.error(request, "Cart does not exist.", extra_tags="alert-danger")
        return HttpResponseRedirect("/store/cart/")

templates/store/all_product.html
{% extends 'base.html' %}
{% load static %}

{% block page_header %} ALL PRODUCTS {% endblock %}

{% block content %}
<div class="row">
    <!-- Card Projects -->
    {% for product in products %}
    <div class="col-lg-3">
        <div class="card">
            <div class="card-image">
                <!--<img class="img-responsive card-inside-image" src="http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0Bx4BSt6jniD7TDlCYzRROE84YWM/materialdesign_introduction.png">-->
                <img class="img-responsive card-inside-image" src="{{ product.image.url }}">
                <span class="card-title"></span>
            </div>

            <div class="card-content">
                <h4> <a href="{% url 'user_vote' product.id %}?back_url={% url 'all_product' %}"> {{ product.name }} </a> </h4>
                <!--<p> {{ product.description }} </p>-->
                <br />
                <p> <div style="text-align:left;float:left" ><b>{{ product.price }} B</b></div>  <div style="text-align: right;float:right;">&nbsp; <b>{{ product.score }}/10.0 </b> </div> </p>
                <br />
            </div>
            <div class="card-action">
                <a href="#"  class="purchase_modal" id="product_{{ product.id }}" name="{{ product.name }}"> Add to my cart </a>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
	    <div class="modal-content">
		<div class="modal-header">
		    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title" id="myModalLabel">Confirmation</h4>
		</div>
		<div class="modal-body">
                    <form class="form-inline">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label for="Amount"> Amount : </label>
                                <input class="form-control" placeholder="amount" name="amount" type="number">
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group" style="float:right;">
                                <label for="Max"> Max : </label>
                                <input class="form-control" placeholder="amount" name="max_amount" type="number" value="10" disabled>
                            </div>
                        </div>
                    </form>
                    <br />
                    <br />
		</div>
		<div class="modal-footer">
		    <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
		    <button type="button" name="purchase_button" class="btn btn-primary" value='1234'>Add to cart</button>
		</div>
	    </div>
	    <!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
    </div>
    <!-- /.modal -->
</div>


{% endblock %}
{% block css %}
	<link href="{% static 'css/card.css' %}" rel="stylesheet" type="text/css">
{% endblock %}

{% block js %}
<script>
$( document ).ready(function() {
    $("a.purchase_modal").click(function (){
        if(is_authenticated){
            var product_id = $(this).attr('id').replace("product_", "");
            $("#myModalLabel").html("Confirmation - " + $(this).attr('name'));
            $.getJSON("{% url 'all_product' %}/" + product_id, function(product_raw) {
                product = product_raw.fields;
                product.id = product_raw.pk;
                $("input[name=max_amount]").val(product.amount);
                $("button[name=purchase_button]").val(product.id);
                $("#myModal").modal('hide').modal('show');
            });
        }else{
            window.location.assign("{% url 'login_view' %}");
        }
    });
    $("button[name=purchase_button]").click(function() {
        $("#myModal").modal('hide');
        $.ajax({
                url: "{% url 'all_product' %}",
                method: "POST",
                data: { product_id: this.value, amount: $("input[name=amount]").val() },
                dataType: "json",
                success: function (data) {
                    if(data.status == "success"){
                        setAndShowNotificationBar("Successfully add to cart !");
                    }else if(data.status == "invalid amount"){
                        setAndShowNotificationBar("Invalid amount !");
                    }else{
                        setAndShowNotificationBar("Hmm ?");
                    }
                },
                error: function (ajaxContext) {
                        setAndShowNotificationBar("Product not found !");
                }
        });
    });
    $("button#btn_notification").click(function(){ $("#notification_bar").fadeOut();});
});
</script>
{% endblock %}

templates/store/all_track.html
{% extends 'base.html' %}
{% load utils %}

{% block css %}
{% load static %}
<!-- DataTables CSS -->
<link href="{% static 'vendor/datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="{% static 'vendor/datatables-responsive/dataTables.responsive.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

<style>
.popover{
        max-width: 100%; /* Max Width of the popover (depending on the container!) */
}
</style>
{% endblock %}
{% block page_header %} TRACKING {% endblock %}

{% block content %}

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Tracking
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th class="col-lg-1">Order ID</th>
                                        <th class="col-lg-3">Total </th>
                                        <th class="col-lg-3">Date</th>
                                        <th>Status</th>
                                        <th>Button</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for track in tracks %}
                                    <tr class="odd gradeX">
                                        <td>{{ track.id }}</td>
                                        <td>{{ track.order.sum_price }}  Baht</td>
                                        <td>{{ track.date | date:"d/m/Y" }} </td>
                                        <td class="center"> <button type="button" class="btn btn-info btn-xs col-lg-4">{{ track.get_current_state_display }} </button> </td>
                                        <td class="center"> <button type="button" class="btn btn-primary btn-outline btn-xs col-lg-4" data-container="body" data-toggle="popover" data-placement="bottom" data-content="
                                                <table width='100%' class='table table-striped'>
                                                    <thead>
                                                        <tr>
                                                            <th> ID</th>
                                                            <th> Name </th>
                                                            <th> Piece</th>
                                                            <th> Qty   </th>
                                                            <th> Total</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for order in track.order.orderlist_set.all %}
                                                        <tr> 
                                                            <td> {{ forloop.counter }} </td>
                                                            <td> {{ order.product.name }} </td>
                                                            <td> {{ order.product.price }} B </td>
                                                            <td> {{ order.qty }} </td>
                                                            <td> {% mul order.qty order.product.price %} B </td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>

                                                " data-html="true">View</button> </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
{% endblock %}


{% block js %}
  <!-- DataTables JavaScript -->
    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-responsive/dataTables.responsive.js' %}"></script>
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    $("[data-toggle=popover]")
            .popover()
    </script>
{% endblock %}

templates/store/history.html
{% extends 'base.html' %}
{% load utils %}

{% block css %}
{% load static %}
<!-- DataTables CSS -->
<link href="{% static 'vendor/datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">

<!-- DataTables Responsive CSS -->
<link href="{% static 'vendor/datatables-responsive/dataTables.responsive.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

<style>
.popover{
        max-width: 100%; /* Max Width of the popover (depending on the container!) */
}
</style>
{% endblock %}
{% block page_header %} PURCHASE HISTORY {% endblock %}

{% block content %}

            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            History
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-hover" id="dataTables-example">
                                <thead>
                                    <tr>
                                        <th class="col-lg-1">Order ID</th>
                                        <th class="col-lg-3">Sum </th>
                                        <th class="col-lg-3">Date</th>
                                        <th>Status</th>
                                        <th>Button</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for his in history %}
                                    <tr class="odd gradeX">
                                        <td>{{ his.id }} </td>
                                        <td>{{ his.order.sum_price }} Baht </td>
                                        <td>{{ track.date | date:"d/m/Y" }} </td>
                                        <td class="center"> <button type="button" class="btn btn-info btn-xs col-lg-4">Success</button> </td>
                                        <td class="center"> <button type="button" class="btn btn-primary btn-outline btn-xs col-lg-4" data-container="body" data-toggle="popover" data-placement="bottom" data-content="
                                                <table width='100%' class='table table-striped'>
                                                    <thead>
                                                        <tr>
                                                            <th> ID</th>
                                                            <th> Name </th>
                                                            <th> Piece</th>
                                                            <th> Qty   </th>
                                                            <th> Total</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    {% for order in his.order.orderlist_set.all %}
                                                        <tr> 
                                                            <td> {{ forloop.counter }} </td>
                                                            <td> {{ order.product.name }} </td>
                                                            <td> {{ order.product.price }} B</td>
                                                            <td> {{ order.qty }}  </td>
                                                            <td> {% mul order.qty order.product.price %} B</td>
                                                        </tr>
                                                    {% endfor %}
                                                    </tbody>
                                                </table>

                                                " data-html="true">View</button> </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
{% endblock %}


{% block js %}
  <!-- DataTables JavaScript -->
    <script src="{% static 'vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/datatables-responsive/dataTables.responsive.js' %}"></script>
    <script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    $("[data-toggle=popover]")
            .popover()
    </script>
{% endblock %}